name: "Secrets action"
description: "Retrieves secrets from the vault and sets them as environment variables."
inputs:
    access-token:
        description: "The access token for the secrets api."
        required: true
    secrets-names:
        description: "The names of the secrets to retrieve."
        required: true
outputs:
    secrets-values: # output will be available to future steps
        description: "The secrets values."
runs:
    using: "node16"
    main: "dist/index.js"
